---
kind: pipeline
name: '[amd64] make test'
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:2
  name: make cli/test
trigger:
  event:
  - pull_request
  ref:
  - refs/heads/main
type: docker
---
kind: pipeline
name: '[arm64] make test'
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:2
  name: make cli/test
trigger:
  event:
  - pull_request
  ref:
  - refs/heads/main
type: docker
---
kind: signature
hmac: 0f9ad18d24bb36fb80c25e1c95ce80d0744d2820fa6dedcff6ba2faf392de134

...
