---
kind: pipeline
name: '[amd64] make test'
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:2
  name: make cli/test
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: '[arm64] make test'
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:2
  name: make cli/test
trigger:
  event:
  - pull_request
type: docker
---
kind: signature
hmac: ae54e4e9f852f94f3f7cd411812430ea96ad7238f1f638753161305d554e55fa

...
