---
kind: pipeline
name: '[amd64] make test'
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - git submodule update --init --recursive
  image: alpine/git
  name: submodules
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:1
  name: make cli/test
trigger:
  event:
  - pull_request
type: docker
---
kind: pipeline
name: '[arm64] make test'
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - git submodule update --init --recursive
  image: alpine/git
  name: submodules
- commands:
  - uname -a
  - make test
  image: pyroscope/rust_builder_cli:1
  name: make cli/test
trigger:
  event:
  - pull_request
type: docker
---
kind: signature
hmac: f38ec1847fa65566c19f685da7928d2eb5cdc68295236e9a18080032a49edeca

...
