---
kind: pipeline
name: make cli/test
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make cli/test
  image: pyroscope/rust_builder_cli:1
  name: make cli/test
trigger:
  event:
  - pull_request
type: docker
---
kind: signature
hmac: 58c0f9f89e51f693a89d126d95c9fb6c154b9ea1683c33c35add8cb78e44c510

...
