name: CI CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: test
        run: USE_CONTAINER=1 make cli/test