name: CI CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: build & test
        run: make cli/build && make cli/test