[package]
name = "rbspy"
version = "0.1.0"
edition = "2021"

[lib]
name = "rbspy"
crate-type = ["cdylib"]

[dependencies]
#pyroscope = {version = "0.5.2" }
pyroscope = { path = "../../../../" }
#pyroscope_rbspy = { version = "0.2" }
pyroscope_rbspy = { path = "../../../../pyroscope_backends/pyroscope_rbspy" }
ffikit = { path = "../../../ffikit" }
pretty_env_logger = "0.4.0"
inferno = "=0.11.14"

[patch.crates-io]
read-process-memory = {git = "https://github.com/omarabid/read-process-memory.git", branch = "0.1.4-fix"}
rbspy = {git="https://github.com/omarabid/rbspy.git", branch="oncpu-fix"}

[build-dependencies]
cbindgen = "0.20.0"

[profile.release]
opt-level= "z"
debug = false
lto = true
codegen-units = 1
